<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.0" />
    <PackageReference Include="NUnit" Version="4.3.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Mdma.Cli\Mdma.Cli.csproj" />
    <ProjectReference Include="..\..\src\Mdma.Core\Mdma.Core.csproj" />
    <ProjectReference Include="..\Mdma.Core.Tests\Mdma.Core.Tests.csproj" />
  </ItemGroup>
</Project>
